### ISSUE TITLE
bigsur(11.3) can also be used

### ISSUE THREAD

**Issue by xcdd** [RealBlueRex/H81M-K-HD4400-EFI#1]
（My English is not my native language. Please forgive me if I have any grammatical mistakes）

Thank you for sharing!

I have modified some settings of config.plist (especially this motherboard can turn off cfglock, you should also turn off uncfglock support on the plist.), Then you can run bigsur11.3 perfectly with the version you built without any problems.

In addition, I use the recovery version to complete the installation,and used a rx560 to complete the graphics driver (CPU is E3), hope to help you!

plist: https://mirror1.54xz.cc/%E4%B8%B4%E6%97%B6/20210429/config.plist

![](https://mirror1.54xz.cc/%E4%B8%B4%E6%97%B6/20210429/image.png)

**Comment by ghost** [comment]
Thank you for your help with my EFI! :D
